// This file is autogenerated via the `commonjs` Grunt task. You can require() this file in a CommonJS environment.
require('../../js/transition.js')
require('../../js/alert.js')
require('../../js/button.js')
require('../../js/carousel.js')
require('../../js/collapse.js')
require('../../js/dropdown.js')
require('../../js/modal.js')
require('../../js/tooltip.js')
require('../../js/popover.js')
require('../../js/scrollspy.js')
require('../../js/tab.js')
require('../../js/affix.js')

[[
		{
			field : 'IMG',
			title : '房间头像',
			align : 'center',
			formatter : function(value, row, index) {
				return "<img class='img-rounded' src='/cm/" + value
						+ "' height='80'/>";
			},
			width : "20%"
		}, {
			field : 'TITLE',
			title : '名称',
			align : 'center',
			sortable : true,
			width : "30%"
		}, {
			field : 'OPER',
			title : '操作',
			formatter : function(value, row, index) {

			},
			width : "50%"
		} ]]